<a href="https://colab.research.google.com/github/profteachkids/CHE4071_Fall2023/blob/main/PID_scipy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import numpy as np
import numpy.polynomial.polynomial as P
import scipy.signal as sig
from plotly.subplots import make_subplots

In [34]:
tf1=sig.lti([],[-1],1).to_tf()

In [163]:
def smul(a,b):
    return P.polymul(a[::-1],b[::-1])[::-1]

def sadd(a,b):
    return P.polyadd(a[::-1],b[::-1])[::-1]

def series(tf1,tf2):
    return sig.lti(smul(tf1.num,tf2.num),smul(tf1.den,tf2.den))

def parallel(tf1,tf2):
    return sig.lti(sadd(smul(tf1.num,tf2.den),smul(tf2.num,tf1.den)),
                   smul(tf1.den,tf2.den))

def feedback(f,b):
    d = parallel(sig.lti(f.den,f.num), b)
    return sig.lti(d.den,d.num)

def PID(Kc, taui, taud=0.):
    return sig.lti([Kc*taui*taud, Kc*taui, Kc],[taui, 0])

In [169]:
Gp = sig.lti(1,[2,1])
Gc = PID(1,0.1)
Gm = sig.lti(1,1)
fb=feedback(series(Gc, Gp), Gm)
t,y=fb.step(T=np.linspace(0,10,100))
fig=make_subplots()
fig.add_scatter(x=t,y=y,mode='lines')
fig.update_layout(width=800,height=600,template='plotly_dark')

In [158]:
series(series(Gc,Gp),Gm)

TransferFunctionContinuous(
array([5.e-01, 5.e-11]),
array([1. , 0.5, 0. ]),
dt: None
)

In [159]:
parallel(series(series(Gc,Gp),Gm),sig.lti(1,1))

TransferFunctionContinuous(
array([1.e+00, 1.e+00, 5.e-11]),
array([1. , 0.5, 0. ]),
dt: None
)

In [160]:
fb

TransferFunctionContinuous(
array([5.0e-01, 2.5e-01, 2.5e-11, 0.0e+00]),
array([1.0e+00, 1.5e+00, 5.0e-01, 2.5e-11, 0.0e+00]),
dt: None
)

In [120]:
tf1=sig.lti([2],[3,1])
tf2=sig.lti([-1],[1,1])
sum=parallel(tf1,tf2)

In [121]:
t,y=parallel(tf1,tf2).step()
fig=make_subplots()
fig.add_scatter(x=t,y=y,mode='lines')
fig.update_layout(width=800,height=600,template='plotly_dark')