<a href="https://colab.research.google.com/github/profteachkids/CHE4071_Fall2023/blob/main/StateSpace_TransferFunction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import jax
jax.config.update('jax_enable_x64',True)
import jax.numpy as jnp
import numpy as np
from scipy.optimize import root

In [13]:
alpha1 = 1.5
A1 = 2.
vec_in = jnp.array([1.2])

def rhs(t, vec_out, vec_in):
    h1 = vec_out
    q1 = vec_in
    return (-alpha1*(h1**0.5) + q1)/A1

In [14]:
rhs(0., jnp.array([1.]), vec_in)

Array([-0.15], dtype=float64)

In [17]:
res=root(lambda vec_out: rhs(0., vec_out, vec_in), jnp.array([1.]))
vec_out_ss = res.x

In [23]:
drhs_dout = jax.jacobian(rhs, 1)
drhs_din = jax.jacobian(rhs, 2)

In [22]:
drhs_dout(0., vec_out_ss, vec_in)

Array([[-0.46875]], dtype=float64)

In [24]:
drhs_din(0., vec_out_ss, vec_in)

Array([[0.5]], dtype=float64)